set -ex 
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs0.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs1.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs2.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs3.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs4.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs5.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs6.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs7.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs8.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs9.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs10.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs11.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs12.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs13.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs14.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs15.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs16.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs17.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs18.sh
/code/tcrp_model/created_models/created_models_GDSC1_PDTC_supp/baseline_cmd/subcommands/subcommands_baseline_drugs19.sh

