set -ex
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug BX-795 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug BX-795 --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.001 --layer 2 --run_name 210803_drug-baseline-models
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug JNJ-26854165 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models		
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug JNJ-26854165 --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.001 --layer 1 --run_name 210803_drug-baseline-models
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug KU-55933 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models		
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug KU-55933 --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.01 --inner_lr 0.1 --layer 2 --run_name 210803_drug-baseline-models
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug Sorafenib --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug Sorafenib --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.01 --inner_lr 0.1 --layer 2 --run_name 210803_drug-baseline-models
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug CHIR-99021 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug CHIR-99021 --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.001 --layer 2 --run_name 210803_drug-baseline-models
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug BMS-754807 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
    python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug BMS-754807 --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.001 --layer 1 --run_name 210803_drug-baseline-models
    python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug JQ1 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug JQ1 --K 10 --num_trials 20 --num_updates 20  --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.001 --layer 1 --tissue_num 6 --run_name 210803_drug-baseline-models	
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug MK-2206 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug MK-2206 --K 10 --num_trials 20 --tissue_num 6 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.001 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug Embelin --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug Embelin --K 10 --num_trials 20 --num_updates 20  --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.01 --layer 1 --tissue_num 6 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug FK866 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug FK866 --K 10 --num_trials 20 --tissue_num 6 --meta_batch_size 15 --meta_lr 0.1 --inner_lr 0.1 --layer 2 --run_name 210803_drug-baseline-models
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug ZM-447439 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models		
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug ZM-447439 --K 10 --num_trials 20 --tissue_num 6 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.001 --layer 1 --run_name 210803_drug-baseline-model		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug SB_216763 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug SB_216763 --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.1 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug 681640 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug 681640 --K 10 --num_trials 20 --tissue_num 6 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.1 --layer 1 --run_name 210803_drug-baseline-models 		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug SL_0101-1 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug SL_0101-1 --K 10 --num_trials 20 --tissue_num 6 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.1 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug AZ628 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug AZ628 --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.1 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug GSK269962A --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug GSK269962A --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.001 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug AZD7762 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug AZD7762 --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.1 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug Camptothecin --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug Camptothecin --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.001 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug BI-2536 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug BI-2536 --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.001 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug Bosutinib --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug Bosutinib --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.01 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug Gefitinib --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug Gefitinib --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.01 --inner_lr 0.01 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug RO-3306 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug RO-3306 --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.01 --inner_lr 0.1 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug TW_37 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug TW_37 --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.01 --inner_lr 0.001 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug AMG-706 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug AMG-706 --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.01 --inner_lr 0.001 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug GW_441756 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug GW_441756 --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.01 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug AG-014699 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug AG-014699 --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.01 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug CEP-701 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug CEP-701 --K 10 --num_trials 20 --tissue_num 20 --meta_batch_size 10 --meta_lr 0.01 --inner_lr 0.1 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug GSK-1904529A --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug GSK-1904529A --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.1 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug PD-173074 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug PD-173074 --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.001 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug PLX4720 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug PLX4720 --K 10 --num_trials 20 --tissue_num 6 --meta_batch_size 10 --meta_lr 0.001 --inner_lr 0.01 --layer 1 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug PD-0332991 --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug PD-0332991 --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.01 --inner_lr 0.001 --layer 2 --run_name 210803_drug-baseline-models		
python /root/capsule/code/tcrp_model/pipelines/generate_fewshot_samples.py --dataset GDSC1_PDTC --tissue PDTC --drug Axitinib --K 10 --num_trials 20 --run_name 210803_drug-baseline-models
python3 /root/capsule/code/tcrp_model/model/supp_MAML_DRUG.py --dataset GDSC1_PDTC --tissue PDTC --drug Axitinib --K 10 --num_trials 20 --tissue_num 12 --meta_batch_size 10 --meta_lr 0.1 --inner_lr 0.01 --layer 2 --run_name 210803_drug-baseline-models